<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tienda Electronica</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" rel="stylesheet">
  <link rel="stylesheet" href="assets/styles.css">
</head>
<body>

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="<?= BASE_URL ?>"><i class="bi bi-cart-fill"></i> Tienda electronica</a>
      <div class="navbar-nav me-auto">
        <a class="nav-link active" href="<?= BASE_URL ?>">Productos</a>
      </div>
      <div class="navbar-nav">
        <span class="navbar-text me-3"><i class="bi bi-person-circle"></i> <?php if($this->user): ?><?=$this->user->email?> <?php else: ?> <a href="<?= BASE_URL ?>login_form" >Login</a> <?php endif; ?></span>    
        <span class="navbar-text me-3"></i> <?php if($this->user): ?><?php else: ?> <a href="<?= BASE_URL ?>registro_form" >Registrarse</a> <?php endif; ?></span>
        <a class="nav-link" href="<?= BASE_URL ?>/cerrar"><i class="bi bi-box-arrow-right"></i> Cerrar sesión</a>
      </div>

    </div>
  </nav>
