<div class="card h-100">
    <div class="card-header bg-primary text-white">
        <h5 class="mb-0">Nuevo producto</h5>
    </div>
    <div class="card-body">
        <form method="POST" action="<?= BASE_URL ?>editProfile/<?= $vendor->id_vendedor ?>">
            <div class="mb-3">
                <label class="form-label">Nombre <span class="text-danger">*</span></label>
                <input required name="name" type="text" class="form-control" value="<?= $vendor->nombre ?>">
            </div>

            <div class="mb-3">
                <label class="form-label">email <span class="text-danger">*</span></label>
                <input required name="email" class="form-control" type="text" value="<?= $vendor->email ?>"></textarea>
            </div>

             <div class="mb-3">
                <label class="form-label">direccion <span class="text-danger">*</span></label>
                <input required name="adress" class="form-control" type="text" value="<?= $vendor->direccion ?>"></textarea>
            </div>

            <div class="mb-3">
                <label class="form-label">telefono de contacto <span class="text-danger">*</span></label>
                <input required name="phoneNumber" class="form-control" type="number" value="<?= $vendor->tel_contacto ?>"></textarea>
            </div>

            <div class="mb-3">
                <label class="form-label">informacion <span class="text-danger">*</span></label>
                <textarea required name="info" class="form-control" rows="5" ><?= $vendor->informacion ?></textarea>
            </div>

           <div class="d-flex gap-2">
                <button type="submit" class="btn btn-primary">Editar Perfil</button>
                <button type="reset" class="btn btn-outline-secondary">Limpiar</button>
            </div>
        </form>
    </div>
</div>