<div class="card">
   <div class="card-header bg-primary text-white">
     <h5 class="mb-0">Producto (<?php $product->nombre; ?>)</h5>
   </div>

   <table class="table table-hover mb-0 align-middle">
     <thead class="table-light">
       <tr>
         <th style="width: 60px;">#</th>
         <th style="width: 120px;">Nombre</th>
         <th style="width: 150px;">Descripcion</th>
         <th style="width: 140px;">Categoria</th>
         <th style="width: 160px;">Precio</th>
         <th style="width: 150px;">Descuento</th>
         <th style="width: 140px;">Publicacion</th>
         <th style="width: 160px;">Vendedor</th>
        <?php if(isset($_SESSION['id'])){?><th style="width: 160px;">Accion</th><?php } ?>
       </tr>
     </thead>

      <img src=<?= htmlspecialchars($product->direccion_img);?> alt="img producto" style="width: 300px; height:300px; align-self:center;">
      
     <tbody>
         <tr>
           <td>
             <strong>#<?= htmlspecialchars($product->id_producto); ?></strong>
           </td>

           <td>
             <?= htmlspecialchars($product->nombre); ?>
           </td>

           <td>
            <?= htmlspecialchars($product->descripcion); ?>
           </td>

           <td>

               <?php $i = 0;  while ($categories[$i]->id_categoria != $product->id_categoria){ $i++;}?> <?= htmlspecialchars($categories[$i]->nombre); ?>

           </td>
           
            <td>
               <?= htmlspecialchars($product->precio - ($product->precio*($product->descuento/100))); ?>
           </td>

            <td>
               <?= htmlspecialchars($product->descuento); ?> %
           </td>

           <td>
               <?= htmlspecialchars($product->fecha_publicacion); ?>
           </td>

           <td>
            <?= $i = 0;  while ($vendors[$i]->id_vendedor != $product->id_vendedor){ $i++;} ?>
             <a href="<?= BASE_URL ?>vendedor/<?=$vendors[$i]->nombre; ?>"><?=htmlspecialchars($vendors[$i]->nombre); ?></a>
           </td>

           <td>
            <?php if(isset($_SESSION['id']) && ($_SESSION['id'] === $product->id_vendedor)){?>
             <a href="<?= BASE_URL ?>deleteProduct/<?= $product->id_producto ?>" class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></a>
           </td>
         </tr>
       <?php } ?>
         </tr>
     </tbody>
   </table>
 </div>