<?php require __DIR__ . '/layout/header.phtml' ?>

<main class="container mt-4">

    <div class="card h-100">
        <div class="card-header bg-primary text-white">
            <h5 class="mb-0">Login</h5>
        </div>
        <div class="card-body">
            <form method="POST" action="<?= BASE_URL ?>registro">
                <div class="mb-3">
                    <label class="form-label">Nombre <span class="text-danger">*</span></label>
                    <input required name="name" type="text" class="form-control" placeholder="nombre">
                </div>
                <div class="mb-3">
                    <label class="form-label">E-mail <span class="text-danger">*</span></label>
                    <input required name="email" type="text" class="form-control" placeholder="user@mail.com">
                </div>
                <div class="mb-3">
                    <label class="form-label">Contraseña <span class="text-danger">*</span></label>
                    <input required name="password" type="password" class="form-control" placeholder="password">
                </div>
                <div class="mb-3">
                    <label class="form-label">Direccion <span class="text-danger">*</span></label>
                    <input required name="adress" type="text" class="form-control" placeholder="Direccion Ejemplo - 123">
                </div>
                <div class="mb-3">
                    <label class="form-label">Telefono de contacto <span class="text-danger">*</span></label>
                    <input required name="phoneNumber" type="tel" class="form-control" pattern="[+]{1}[0-9]{8,12}" placeholder="+540001111">
                </div>
                <div class="mb-3">
                    <label class="form-label">Informacion <span class="text-danger">*</span></label>
                    <input required name="information" type="text" class="form-control" placeholder="sobre nosotros...">
                </div>
                
                <div class="d-flex gap-2">
                    <button type="submit" class="btn btn-primary">Registrarse</button>
                    <button type="reset" class="btn btn-outline-secondary">Limpiar</button>
                </div>
            </form>
        </div>
    </div>

</main>

<?php require __DIR__ . '/layout/footer.phtml' ?>