        
    <table class="table table-hover mb-0 align-middle">
     <thead class="table-light">
       <tr>
         <th style="width: 60px;">#</th>
         <th style="width: 120px;"><td>Nombre: <?= htmlspecialchars($vendor->nombre) ?></td></th>
         <th style="width: 150px;"><td>email: <?= htmlspecialchars($vendor->email) ?></td></th>
         <th style="width: 140px;"><td>direccion: <?= htmlspecialchars($vendor->direccion) ?> </td></th>
         <th style="width: 160px;"><td>tel_contacto: <?= htmlspecialchars($vendor->tel_contacto) ?></td></th>
         <th style="width: 150px;"><td>informacion: <?= htmlspecialchars($vendor->informacion) ?></td></th>
       </tr>
     </thead>

  <div class="card">
    <div class="card-header bg-primary text-white">
    <h5 class="mb-0">Productos (<?= $count ?>)</h5>
  </div>

   <table class="table table-hover mb-0 align-middle">
     <thead class="table-light">
       <tr>
         <th style="width: 60px;">#</th>
         <th style="width: 120px;">Nombre</th>
         <th style="width: 150px;">Descripcion</th>
         <th style="width: 140px;">Categoria</th>
         <th style="width: 160px;">Precio</th>
         <th style="width: 150px;">Descuento</th>
         <th style="width: 140px;">Publicacion</th>
         <th style="width: 160px;">Vendedor</th>
        <?php if(isset($_SESSION['id'])){?><th style="width: 160px;">Accion</th><?php } ?>
       </tr>
     </thead>

     <tbody>
       <?php  foreach ($products as $product) { ?>
         <tr>
           <td>
             <strong>#<?= htmlspecialchars($product->id_producto); ?></strong>
           </td>

           <td>
             <a href="<?= BASE_URL ?>producto/<?= urlencode($product->id_producto) ?>/<?= urlencode($product->nombre) ?>"><?= htmlspecialchars($product->nombre); ?></a>
           </td>

           <td>
             <?php $i = 0;  while ($categories[$i]->id_categoria != $product->id_categoria){ $i++;}?> <?= htmlspecialchars($categories[$i]->nombre); ?>
           </td>

           <td>
            <?= htmlspecialchars($product->descripcion); ?>
           </td>

           <td>

               <?= htmlspecialchars($categories[$product->id_categoria - 1]->nombre); ?>

           </td>
           
            <td>
               <?= htmlspecialchars($product->precio - ($product->precio*($product->descuento/100)) ); ?>
           </td>

            <td>
               <?= htmlspecialchars($product->descuento); ?> %
           </td>

           <td>
               <?= htmlspecialchars($product->fecha_publicacion); ?>
           </td>

           <td>
                <?=htmlspecialchars($vendor->nombre); ?>
           </td>
           <td>
            <?php if(isset($_SESSION['id']) && ($_SESSION['id'] === $product->id_vendedor)){?>
             <a href="editar.html" class="btn btn-sm btn-outline-primary"><i class="bi bi-pencil"></i></a>
             <a href="delete/<?= $product->id_producto ?>" class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></a>
           </td>
         </tr>
       <?php } }?>
     </tbody>
   </table>
 </div>